// O'zbek tilidagi barcha matnlar
export const uz = {
  appName: "Birga Tomosha",
  tagline: "Do'stlaringiz bilan bir vaqtda kino ko'ring",
  // Auth
  signIn: "Kirish",
  signUp: "Ro'yxatdan o'tish",
  signOut: "Chiqish",
  email: "Elektron pochta",
  password: "Parol",
  displayName: "Ismingiz",
  authError: "Xatolik yuz berdi",
  invalidCreds: "Email yoki parol noto'g'ri",
  emailExists: "Bu email allaqachon ro'yxatdan o'tgan",
  weakPassword: "Parol kamida 6 ta belgidan iborat bo'lishi kerak",
  haveAccount: "Hisobingiz bormi?",
  noAccount: "Hisobingiz yo'qmi?",
  showPassword: "Parolni ko'rsatish",
  hidePassword: "Parolni yashirish",
  // Forgot password / OTP
  forgotPassword: "Parolni unutdingizmi?",
  backToSignIn: "Kirishga qaytish",
  sendCode: "Kodni yuborish",
  sendingCode: "Yuborilmoqda...",
  codeSent: "Emailingizga tasdiqlash kodi yuborildi",
  otpCode: "6 xonali kod",
  newPassword: "Yangi parol",
  setNewPassword: "Yangi parol o'rnatish",
  updatePassword: "Parolni yangilash",
  passwordUpdated: "Parolingiz muvaffaqiyatli yangilandi!",
  invalidOtp: "Kod noto'g'ri yoki muddati o'tgan",
  recoveryHint: "Iltimos, yangi parolingizni kiriting",
  // Dashboard
  myRooms: "Mening xonalarim",
  createRoom: "Yangi xona yaratish",
  roomName: "Xona nomi",
  noRooms: "Hali xona yaratmagansiz",
  enter: "Kirish",
  delete: "O'chirish",
  // Room
  copyLink: "Havolani nusxalash",
  linkCopied: "Havola nusxalandi",
  theaterMode: "Kino rejimi",
  exitTheater: "Kino rejimidan chiqish",
  leave: "Chiqish",
  uploadVideo: "Video yuklash",
  externalUrl: "Tashqi URL qo'shish",
  pasteUrl: "mp4 yoki webm havolasini joylashtiring",
  invalidUrl: "Iltimos, to'g'ri .mp4 yoki .webm havolasini kiriting",
  uploading: "Yuklanmoqda",
  noVideo: "Hali video tanlanmagan",
  noVideoHint: "Xona yaratuvchisi video yuklashi yoki havola qo'shishi kerak",
  hostOnly: "Faqat xona yaratuvchisi boshqaradi",
  guests: "Mehmonlar",
  host: "Yaratuvchi",
  participants: "Ishtirokchilar",
  chat: "Chat",
  cameras: "Kameralar",
  sendMessage: "Xabar yozing...",
  send: "Yuborish",
  showPanel: "Kamera/Chatni ko'rsatish",
  hidePanel: "Yashirish",
  // Status
  joined: "Kirdi",
  loadingStatus: "Yuklanmoqda",
  ready: "Tayyor",
  waitingFor: (name: string) => `Kuting, ${name} tarmog'i qotib qoldi...`,
  // Camera
  micOn: "Mikrofonni o'chirish",
  micOff: "Mikrofonni yoqish",
  camOn: "Kamerani o'chirish",
  camOff: "Kamerani yoqish",
  cameraOffLabel: "Kamera o'chirilgan",
  permError: "Kamera va mikrofonga ruxsat bering",
  permRetry: "Qayta urinish",
  watchOnly: "Faqat tomosha rejimi",
  // Player overlay
  volume: "Ovoz balandligi",
  play: "O'ynatish",
  pause: "Pauza",
  // Action toasts
  joinedRoom: (name: string) => `${name} xonaga qo'shildi`,
  leftRoom: (name: string) => `${name} xonadan chiqdi`,
  playedVideo: (name: string) => `${name} videoni ishga tushirdi`,
  pausedVideo: (name: string) => `${name} videoni pauza qildi`,
  cameraOn: (name: string) => `${name} kamerasini yoqdi`,
  cameraOff: (name: string) => `${name} kamerasini o'chirdi`,
  micOnToast: (name: string) => `${name} mikrofonini yoqdi`,
  micOffToast: (name: string) => `${name} mikrofonini o'chirdi`,
  // Nuke
  nuke: "Serverdan tozalash",
  nukeWarning: "Diqqat! Bu video serverdan butunlay o'chiriladi. Rozimisiz?",
  confirm: "Ha, o'chirish",
  cancel: "Bekor qilish",
  videoDeleted: "Video o'chirildi",
  // Errors
  networkError: "Internet aloqasi yo'q",
  reconnecting: "Qayta ulanmoqda...",
  unknownError: "Noma'lum xatolik",
  notFound: "Topilmadi",
  goHome: "Bosh sahifa",
  loading: "Yuklanmoqda...",
  hostLeft: "Xona yaratuvchisi chiqib ketdi",
  // Moderation
  localMute: "Ovozni o'chirish",
  localUnmute: "Ovozni yoqish",
  forceMute: "Ovozini o'chirish",
  kick: "Xonadan chetlatish",
  kickedMessage: "Siz xonadan chetlatildingiz",
  mutedByHost: "Yaratuvchi mikrofoningizni o'chirdi",
  fullscreen: "To'liq ekran",
  hostActions: "Yaratuvchi amallari",
  // Super Admin
  superAdmin: "Super Admin",
  manageServer: "Serverni Boshqarish",
  serverFiles: "Serverdagi fayllar",
  noFiles: "Serverda fayllar yo'q",
  fileSize: "Hajmi",
  deleteAll: "Barchasini tozalash",
  fileDeleted: "Fayl serverdan o'chirildi",
  allFilesDeleted: "Barcha fayllar o'chirildi",
  deleteAllConfirm: "Haqiqatan barcha fayllarni o'chirmoqchimisiz?",
  loadingFiles: "Fayllar yuklanmoqda...",
  // Friends
  friends: "Do'stlar",
  myFriends: "Mening do'stlarim",
  addFriend: "Do'st qo'shish",
  searchUserPlaceholder: "Email yoki ism bo'yicha qidiring",
  search: "Qidirish",
  sendFriendRequest: "Do'stlik so'rovi",
  friendRequestSent: "Do'stlik so'rovi yuborildi",
  friendRequestReceived: (name: string) => `${name} sizni do'st sifatida qo'shmoqchi`,
  incomingRequests: "Kelgan so'rovlar",
  noFriends: "Hali do'stlaringiz yo'q",
  noOnlineFriends: "Onlayn do'stlar yo'q",
  noRequests: "Yangi so'rovlar yo'q",
  accept: "Qabul qilish",
  decline: "Rad etish",
  online: "Onlayn",
  offline: "Oflayn",
  friendAdded: (name: string) => `${name} endi do'stingiz`,
  friendDeclined: "Rad etildi",
  alreadyFriends: "Allaqachon do'stsiz",
  userNotOnline: "Foydalanuvchi hozir onlayn emas",
  // Invite
  inviteFriend: "Taklif qilish",
  inviteFriends: "Do'stlarni taklif qilish",
  invite: "Taklif",
  inviteSent: (name: string) => `${name}'ga taklif yuborildi`,
  inviteReceived: (name: string, room: string) => `${name} sizni '${room}' xonasiga chaqiryapti!`,
  inviteAccepted: "Qabul qilindi",
  inviteDeclined: "Rad etildi",
  noResults: "Hech kim topilmadi",
  // Profile
  profile: "Profil",
  myProfile: "Mening profilim",
  nickname: "Foydalanuvchi nomi",
  avatar: "Profil rasmi",
  uploadAvatar: "Rasm yuklash",
  saveProfile: "Saqlash",
  profileUpdated: "Profil yangilandi",
  profileError: "Profilni yangilab bo'lmadi",
  // Lobby
  activeRooms: "Faol Xonalar",
  noActiveRooms: "Hozir faol ommaviy xonalar yo'q",
  publicRoom: "Ommaviy",
  privateRoom: "Yopiq",
  privacyToggle: "Yopiq xona",
  joinRoom: "Qo'shilish",
  joinRequestSent: "So'rov yuborildi, kuting...",
  joinRequestIncoming: (name: string) => `${name} xonangizga qo'shilmoqchi`,
  joinAccepted: "Qabul qilindi",
  joinDeclined: "Rad etildi",
  hostNotResponding: "Xona yaratuvchisi javob bermadi",
  // Permissions
  grantControl: "Boshqarish huquqini berish",
  revokeControl: "Boshqarish huquqini olish",
  controlGranted: (name: string) => `${name}ga boshqarish huquqi berildi`,
  controlRevoked: (name: string) => `${name}dan boshqarish huquqi olindi`,
  // YouTube / player
  youtubeOrFile: "YouTube ssilkasini kiriting yoki video URL...",
  loadVideo: "Yuklash",
  invalidVideoUrl: "YouTube havolasi yoki .mp4/.webm URL kerak",
  // LiveKit
  connectingMedia: "Aloqa o'rnatilmoqda...",
  mediaConnectError: "Aloqa o'rnatilmadi",
  // Local file
  uploadLocalFile: "Fayl yuklash",
  localFileLoaded: "Mahalliy fayl yuklandi (faqat sizda ko'rinadi, vaqt sinxron)",
  // Force mute
  muteParticipant: "Ovozini o'chirish",
  forcedMutedToast: "Sizning mikrofoningiz xona egasi tomonidan o'chirildi",
  // Media search
  searchMedia: "Kino/Anime Qidirish",
  searchPlaceholder: "Kino yoki anime nomi...",
  searchAnime: "Anime",
  searchMovies: "Kino",
  searchUnavailable: "Qidiruv xizmati hozir ishlamayapti",
  streamUnavailable: "Oqim havolasi topilmadi",
  noSearchResults: "Hech nima topilmadi",
  searching: "Qidirilmoqda...",
  loadStream: "Yuklash",
} as const;
